---
title: "stat133-final-store salary"
author: "Zihan Chen"
date: "November 14, 2016"
output: html_document
---
library(readr)
getwd()

ATL <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-ATL.csv", header=TRUE, sep=",")

BOS <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-BOS.csv", header=TRUE, sep=",")

BRK <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-BRK.csv", header=TRUE, sep=",")

CHI <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-CHI.csv", header=TRUE, sep=",")

CHO <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-CHO.csv", header=TRUE, sep=",")

CLE <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-CLE.csv", header=TRUE, sep=",")

DAL <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-DAL.csv", header=TRUE, sep=",")

DEN <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-DEN.csv", header=TRUE, sep=",")

DET <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-DET.csv", header=TRUE, sep=",")

GSW <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-GSW.csv", header=TRUE, sep=",")

HOU <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-HOU.csv", header=TRUE, sep=",")

IND <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-IND.csv", header=TRUE, sep=",")

LAC <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-LAC.csv", header=TRUE, sep=",")

LAL <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-LAL.csv", header=TRUE, sep=",")

MEM <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-MEM.csv", header=TRUE, sep=",")

MIA <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-MIA.csv", header=TRUE, sep=",")

MIL <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-MIL.csv", header=TRUE, sep=",")

MIN <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-MIN.csv", header=TRUE, sep=",")

NOP <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-NOP.csv", header=TRUE, sep=",")

NYK <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-NYK.csv", header=TRUE, sep=",")

OKC <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-OKC.csv", header=TRUE, sep=",")

ORL <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-ORL.csv", header=TRUE, sep=",")

PHI <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-PHI.csv", header=TRUE, sep=",")

PHO <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-PHO.csv", header=TRUE, sep=",")

POR <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-POR.csv", header=TRUE, sep=",")

SAC <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-SAC.csv", header=TRUE, sep=",")

TOR <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-TOR.csv", header=TRUE, sep=",")

UTA <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-UTA.csv", header=TRUE, sep=",")

WAS <- read.csv(file = "/Users/apple/Documents/college/FALL 2016/stat 133/final/stat133-final-proj/data/rawdata/salary-data/salaries-WAS.csv", header=TRUE, sep=",")

